package day11.part2

import org.junit.jupiter.api.Test

import org.junit.jupiter.api.Assertions.*

class Day11part2KtTest {

    @Test
    fun test10() {
        val input = """
            ...#......
            .......#..
            #.........
            ..........
            ......#...
            .#........
            .........#
            ..........
            .......#..
            #...#.....
        """.trimIndent().lines()
        assertEquals(1030, solve(input, 10))
    }

    @Test
    fun test100() {
        val input = """
            ...#......
            .......#..
            #.........
            ..........
            ......#...
            .#........
            .........#
            ..........
            .......#..
            #...#.....
        """.trimIndent().lines()
        assertEquals(8410, solve(input, 100))
    }
}
